---
- name: Add system group for zigbee2MQTT
  become: true
  ansible.builtin.group:
    name: "{{ zigbee2mqtt_group }}"
    state: present
    system: true

- name: Add system user for zigbee2MQTT
  become: true
  ansible.builtin.user:
    name: "{{ zigbee2mqtt_user }}"
    state: present
    system: true
    create_home: true
    skeleton: false
    home: "{{ zigbee2mqtt_home }}"
    shell: "{{ zigbee2mqtt_shell }}"
    group: "{{ zigbee2mqtt_group }}"
    groups:
      - dialout

- name: Ensure zigbee2MQTT state directory exists
  become: true
  ansible.builtin.file:
    path: "{{ zigbee2mqtt_home }}/data"
    state: directory
    group: "{{ zigbee2mqtt_group }}"
    owner: "{{ zigbee2mqtt_user }}"

- name: Copy configuration file
  become: true
  ansible.builtin.template:
    src: zigbee2mqtt_configuration.yaml.j2
    dest: "{{ zigbee2mqtt_home }}/data/configuration.yaml"
    owner: "{{ zigbee2mqtt_user }}"
    group: "{{ zigbee2mqtt_group }}"

- name: Copy configuration secrets
  become: true
  ansible.builtin.template:
    src: zigbee2mqtt_secrets.yaml.j2
    dest: "{{ zigbee2mqtt_home }}/data/secrets.yaml"
    owner: "{{ zigbee2mqtt_user }}"
    group: "{{ zigbee2mqtt_group }}"
    mode: 0640
  when: >
    mqtt_user is defined or
    mqtt_password is defined or
    zigbee2mqtt_frontend_auth_token is defined or
    zigbee_network_key is defined

- name: Clone Zigbee2MQTT repository
  become: true
  become_user: "{{ zigbee2mqtt_user }}"
  ansible.builtin.git:
    dest: "{{ zigbee2mqtt_path }}"
    repo: "{{ zigbee2mqtt_repository }}"
    depth: 1
    clone: true
    update: false
  register: z_repo_cloned

- name: Check installed node.js packages
  become: true
  become_user: "{{ zigbee2mqtt_user }}"
  ansible.builtin.command:
    chdir: "{{ zigbee2mqtt_path }}"
    cmd: npm list --json
  register: z_check_npm_list
  no_log: true
  failed_when: not z_check_npm_list.changed

- name: Install Zigbee2MQTT
  become: true
  become_user: "{{ zigbee2mqtt_user }}"
  community.general.npm:
    ci: true
    path: "{{ zigbee2mqtt_path }}"
  when: z_repo_cloned.changed or
    z_check_npm_list.rc == 1
